name: "NeoFS Netmap"
safemethods: ["innerRingList", "epoch", "netmap", "netmapCandidates", "snapshot", "snapshotByEpoch", "config", "listConfig", "version"]
permissions:
  - methods: ["update", "newEpoch"]
events:
  - name: AddPeer
    parameters:
      - name: nodeInfo
        type: ByteArray
  - name: AddPeerSuccess
    parameters:
      - name: publicKey
        type: PublicKey
  - name: UpdateState
    parameters:
      - name: state
        type: Integer
      - name: publicKey
        type: PublicKey
  - name: UpdateStateSuccess
    parameters:
      - name: publicKey
        type: PublicKey
      - name: state
        type: Integer
  - name: NewEpoch
    parameters:
      - name: epoch
        type: Integer
