name: "NeoFS Subnet"
safemethods: ["version"]
permissions:
  - methods: ["update"]
events:
  - name: SubnetPut
    parameters:
      - name: ownerKey
        type: PublicKey
      - name: info
        type: ByteArray

